services:
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app # target container root directory for ng reload
    ports:
      - "8100:8100"
  api:
    build: ./server
    volumes:
      - type: bind
        source: ./server
        target: /app # target container root directory for air
    ports:
      - "3000:3000"
