services:
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "8100:8100"
  api:
    build: ./server
    volumes:
      - type: bind
        source: ./server
        target: /app
    ports:
      - "3000:3000"
